server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    max-http-post-size: 50MB

spring:
  application:
    name: SBB
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


  datasource:
    url: jdbc:mysql://localhost:3306/Studyshare ?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lsy27662766




  ####################################
  # JPA ??
  ####################################

  jpa:
    open-in-view: true      #
    hibernate:
      ddl-auto: update     # create, update, ...
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # ?????? ?????? ??
    show-sql: true          # SQL ?? ??
    properties:
      hibernate:
        format_sql: true    # SQL ??? ??